# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bootstrap_builder 0.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "bootstrap_builder".freeze
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jack Neto".freeze, "The Working Group Inc.".freeze]
  s.date = "2018-03-29"
  s.description = "".freeze
  s.email = "jack@twg.ca".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/glyphicons-halflings-white.png",
    "app/assets/images/glyphicons-halflings.png",
    "app/assets/javascripts/bootstrap_builder/bootstrap.js",
    "app/assets/javascripts/bootstrap_builder/bootstrap_builder.js",
    "app/assets/stylesheets/bootstrap_builder/bootstrap-responsive.css",
    "app/assets/stylesheets/bootstrap_builder/bootstrap.css",
    "app/views/bootstrap_builder/_check_box.html.haml",
    "app/views/bootstrap_builder/_default_field.html.haml",
    "app/views/bootstrap_builder/_radio_button.html.haml",
    "app/views/bootstrap_builder/_submit.html.haml",
    "bootstrap_builder.gemspec",
    "lib/bootstrap_builder.rb",
    "lib/bootstrap_builder/builder.rb",
    "lib/bootstrap_builder/configuration.rb",
    "lib/bootstrap_builder/engine.rb",
    "lib/bootstrap_builder/helper.rb",
    "lib/bootstrap_builder/railtie.rb"
  ]
  s.homepage = "http://github.com/twg/bootstrap_builder".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "A Rails form builder that generates Twitter Bootstrap markup and helps keep your code clean".freeze
end

